export default {
  advertisment: {
    id: 0,
    title: "",
    category: "",
    description: "",
    condition: "",
    images: [],
    buy: "",
    owner: "",
    town: "",
    city: "",
    province: "",
    mobile: "",
    landline: "",
    sellerName: "",
    isApproved: 0,
    created_at: "",
    update_at: "",
  },
};
