export default {
  properties: [],
  message: "",
  isLoading: false,
  isError: false,
  property: {
    id: 0,
    tittle: "",
    category: "",
    additional_info: "",
    residential_type: "",
    images: [],
    buy: "",
    owner: "",
    province: "",
    city: "",
    town: "",
    living_area_square_meters: "",
    running_water: "",
    electricity: "",
    restroom: "",
    room_arrangement: "",
    number_of_rooms: "",
    security: "",
    isRentOrSale: "",
    mobile: "",
    landline: "",
    email: "",
    isApproved: 0,
    created_at: "",
    update_at: "",
  },
};
